server:
  port: 8081

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      
      routes:
        - id: usuarios-service
          uri: ${USUARIOS_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/usuarios/**

        - id: monitoreo-service
          uri: ${MONITOREO_SERVICE_URL:http://localhost:8000}
          predicates:
            - Path=/api/analisis/**

        - id: proyectos-service
          uri: ${PROYECTOS_SERVICE_URL:http://localhost:8067}
          predicates:
            - Path=/api/proyectos/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"