apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-app
          image: ratatudela/mi-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # 🌟 CAMBIADO: De NodePort a LoadBalancer
  ports:
    - port: 30080      # 🌟 El puerto real que vas a escribir en tu navegador
      targetPort: 80    # El puerto interno del contenedor de React
  selector:
    app: frontend