apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472  # Corrección para Docker Desktop: Da permisos correctos al volumen de Grafana
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: LoadBalancer # Docker Desktop mapeará esto mágicamente a tu localhost
  selector:
    app: grafana
  ports:
    - port: 3000       # Acceso interno del clúster Y externo en tu navegador: http://localhost:3000
      targetPort: 3000 # Puerto interno del contenedor