apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyectos-deployment
  labels:
    app: proyectos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyectos
  template:
    metadata:
      labels:
        app: proyectos
    spec:
      containers:
        - name: proyectos-app
          image: ratatudela/proyectos-service:v1
          ports:
            - containerPort: 8067
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
---
apiVersion: v1
kind: Service
metadata:
  name: proyectos-service
spec:
  ports:
    - port: 8067
      targetPort: 8067
  selector:
    app: proyectos