spring.application.name=proyectos

spring.datasource.url=jdbc:postgresql://ep-jolly-forest-a4hn1jmr-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_DOr32IgmeUGC

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8067



spring.rabbitmq.host=localhost

spring.rabbitmq.port=5672

spring.rabbitmq.username=guest

spring.rabbitmq.password=guest

spring.rabbitmq.listener.type=simple



spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true


logging.level.org.springframework.amqp=DEBUG

logging.level.com.rabbitmq=DEBUG

# Exponer métricas para el Prometheus
management.endpoints.web.exposure.include=health,prometheus
